#!/bin/bash
# ZooKeeper 安装/卸载模块
# 项目: oneinstack/zookeeper

# 安装 ZooKeeper
Install_ZooKeeper() {
  # 1. 已安装检测
  if [ -e "${zk_install_dir}/bin/zkServer.sh" ]; then
    echo "${CWARNING}ZooKeeper already installed at ${zk_install_dir}${CEND}"
    return 0
  fi
  
  echo "${CMSG}=== Installing ZooKeeper ${zk_ver} ===${CEND}"
  
  # 2. 检测依赖
  Check_Dependencies "${zk_ver}" || return 1
  
  # 3. 创建目录
  mkdir -p "${zk_install_dir}" "${zk_data_dir}" "${zk_log_dir}" "${src_dir}"
  
  # 4. 下载安装包
  src_url="https://archive.apache.org/dist/zookeeper/zookeeper-${zk_ver}/apache-zookeeper-${zk_ver}-bin.tar.gz"
  Download_src || return 1
  
  # 5. 解压部署
  echo "${CMSG}Extracting ZooKeeper...${CEND}"
  tar xzf "${src_dir}/apache-zookeeper-${zk_ver}-bin.tar.gz" -C /tmp/
  
  if [ ! -d "/tmp/apache-zookeeper-${zk_ver}-bin" ]; then
    echo "${CFAILURE}Extract failed!${CEND}"
    return 1
  fi
  
  # 移动到安装目录
  cp -a /tmp/apache-zookeeper-${zk_ver}-bin/* "${zk_install_dir}/"
  rm -rf /tmp/apache-zookeeper-${zk_ver}-bin
  
  # 6. 生成配置文件
  Generate_ZK_Config
  
  # 7. 生成 JVM 配置
  Generate_Java_Env
  
  # 8. 创建系统用户
  if ! id -u zookeeper &>/dev/null; then
    useradd -M -s /sbin/nologin zookeeper
    echo "${CSUCCESS}Created user: zookeeper${CEND}"
  fi
  
  # 9. 设置目录权限
  chown -R zookeeper:zookeeper "${zk_install_dir}" "${zk_data_dir}" "${zk_log_dir}"
  
  # 10. 注册 systemd 服务
  Install_ZK_Service
  
  # 11. 启动服务
  systemctl start zookeeper
  
  # 12. 验证安装
  sleep 3
  Verify_ZK_Install
  
  return $?
}

# 生成 ZooKeeper 配置文件
Generate_ZK_Config() {
  echo "${CMSG}Generating zoo.cfg...${CEND}"
  
  cat > "${zk_install_dir}/conf/zoo.cfg" << EOF
# ZooKeeper Configuration
# Generated by oneinstack/zookeeper

# 基础配置
tickTime=2000
initLimit=10
syncLimit=5

# 数据目录
dataDir=${zk_data_dir}
dataLogDir=${zk_log_dir}

# 客户端端口
clientPort=${zk_client_port}

# Admin Server (3.5.0+)
admin.serverPort=${zk_admin_port}
admin.enableServer=true

# 四字命令白名单
4lw.commands.whitelist=*

# 自动清理快照和日志
autopurge.snapRetainCount=3
autopurge.purgeInterval=1

# 最大客户端连接数
maxClientCnxns=60
EOF

  # 集群模式配置
  if [ "${deploy_mode}" == "cluster" ] && [ -n "${cluster_nodes}" ]; then
    echo "" >> "${zk_install_dir}/conf/zoo.cfg"
    echo "# 集群配置" >> "${zk_install_dir}/conf/zoo.cfg"
    
    for node in ${cluster_nodes}; do
      local node_id="${node%%:*}"
      local node_host="${node#*:}"
      echo "server.${node_id}=${node_host}:${zk_peer_port}:${zk_election_port}" >> "${zk_install_dir}/conf/zoo.cfg"
    done
    
    # 生成 myid 文件
    echo "${myid}" > "${zk_data_dir}/myid"
    echo "${CSUCCESS}Generated myid: ${myid}${CEND}"
  fi
  
  echo "${CSUCCESS}Generated zoo.cfg${CEND}"
}

# 生成 JVM 配置
Generate_Java_Env() {
  echo "${CMSG}Generating java.env...${CEND}"
  
  cat > "${zk_install_dir}/conf/java.env" << EOF
# ZooKeeper JVM Configuration
# Generated by oneinstack/zookeeper

export JAVA_HOME=${JAVA_HOME}
export ZK_SERVER_HEAP=${zk_heap_size%m}

# GC 配置 (推荐 G1GC)
export SERVER_JVMFLAGS="${zk_jvm_opts} -Djava.io.tmpdir=/tmp"

# JMX 配置 (可选)
# export JMXPORT=9999
# export JMXAUTH=false
# export JMXSSL=false
EOF

  echo "${CSUCCESS}Generated java.env${CEND}"
}

# 安装 systemd 服务
Install_ZK_Service() {
  echo "${CMSG}Installing systemd service...${CEND}"
  
  cat > /lib/systemd/system/zookeeper.service << EOF
[Unit]
Description=Apache ZooKeeper Server
Documentation=https://zookeeper.apache.org/doc/current/
After=network.target

[Service]
Type=forking
User=zookeeper
Group=zookeeper

Environment="JAVA_HOME=${JAVA_HOME}"
Environment="ZK_HOME=${zk_install_dir}"
Environment="ZOOCFGDIR=${zk_install_dir}/conf"

ExecStart=${zk_install_dir}/bin/zkServer.sh start
ExecStop=${zk_install_dir}/bin/zkServer.sh stop
ExecReload=${zk_install_dir}/bin/zkServer.sh restart

PIDFile=${zk_data_dir}/zookeeper_server.pid

Restart=on-failure
RestartSec=10

LimitNOFILE=65536
LimitNPROC=65536

[Install]
WantedBy=multi-user.target
EOF

  systemctl daemon-reload
  systemctl enable zookeeper
  
  echo "${CSUCCESS}Systemd service installed${CEND}"
}

# 验证安装
Verify_ZK_Install() {
  echo "${CMSG}Verifying ZooKeeper installation...${CEND}"
  
  # 检查进程
  if ! pgrep -f "zookeeper" > /dev/null; then
    echo "${CFAILURE}ZooKeeper process not running!${CEND}"
    systemctl status zookeeper
    return 1
  fi
  
  # 使用四字命令检查
  local response=$(echo "ruok" | nc -w 2 127.0.0.1 ${zk_client_port} 2>/dev/null)
  
  if [ "${response}" == "imok" ]; then
    echo "${CSUCCESS}=== ZooKeeper installed successfully! ===${CEND}"
    echo ""
    echo "${CMSG}Installation Summary:${CEND}"
    echo "  Version: ${zk_ver}"
    echo "  Install Dir: ${zk_install_dir}"
    echo "  Data Dir: ${zk_data_dir}"
    echo "  Client Port: ${zk_client_port}"
    echo "  Admin Port: ${zk_admin_port}"
    echo "  Deploy Mode: ${deploy_mode}"
    [ "${deploy_mode}" == "cluster" ] && echo "  MyID: ${myid}"
    echo ""
    echo "  Service: systemctl {start|stop|restart|status} zookeeper"
    echo "  Health Check: echo ruok | nc localhost ${zk_client_port}"
    return 0
  else
    echo "${CFAILURE}ZooKeeper health check failed!${CEND}"
    echo "Response: ${response}"
    systemctl status zookeeper
    return 1
  fi
}

# 卸载 ZooKeeper
Uninstall_ZooKeeper() {
  echo "${CMSG}=== Uninstalling ZooKeeper ===${CEND}"
  
  # 停止服务
  if systemctl is-active zookeeper &>/dev/null; then
    echo "Stopping ZooKeeper service..."
    systemctl stop zookeeper
  fi
  
  # 禁用服务
  if systemctl is-enabled zookeeper &>/dev/null; then
    echo "Disabling ZooKeeper service..."
    systemctl disable zookeeper
  fi
  
  # 删除 service 文件
  if [ -f /lib/systemd/system/zookeeper.service ]; then
    rm -f /lib/systemd/system/zookeeper.service
    systemctl daemon-reload
    echo "Removed systemd service"
  fi
  
  # 备份数据目录
  if [ -d "${zk_data_dir}" ]; then
    local backup_name="${zk_data_dir}_bak_$(date +%Y%m%d%H%M)"
    echo "Backing up data directory to: ${backup_name}"
    mv "${zk_data_dir}" "${backup_name}"
  fi
  
  # 删除安装目录
  if [ -d "${zk_install_dir}" ]; then
    echo "Removing install directory: ${zk_install_dir}"
    rm -rf "${zk_install_dir}"
  fi
  
  # 删除日志目录
  if [ -d "${zk_log_dir}" ]; then
    echo "Removing log directory: ${zk_log_dir}"
    rm -rf "${zk_log_dir}"
  fi
  
  # 清理环境变量
  if grep -q "ZOOKEEPER_HOME" /etc/profile; then
    sed -i '/ZOOKEEPER_HOME/d' /etc/profile
    sed -i "s@${zk_install_dir}/bin:@@g" /etc/profile
  fi
  
  # 删除用户 (可选)
  # id -u zookeeper &>/dev/null && userdel zookeeper
  
  echo "${CSUCCESS}ZooKeeper uninstalled successfully!${CEND}"
  [ -n "${backup_name}" ] && echo "${CMSG}Data backup: ${backup_name}${CEND}"
}

# 预览卸载内容
Print_ZooKeeper() {
  echo "${CMSG}The following will be removed:${CEND}"
  [ -d "${zk_install_dir}" ] && echo "  - ${zk_install_dir}"
  [ -d "${zk_data_dir}" ] && echo "  - ${zk_data_dir} (will be backed up)"
  [ -d "${zk_log_dir}" ] && echo "  - ${zk_log_dir}"
  [ -f "/lib/systemd/system/zookeeper.service" ] && echo "  - /lib/systemd/system/zookeeper.service"
}
