# /etc/profile.d/openjdk.sh — generated by dmp_ops/openjdk, DO NOT EDIT MANUALLY
# 占位符由 include/jdk_env.sh 的 Set_JDK_Env() 渲染
#   {{JAVA_HOME}} — 统一软链路径(默认 /usr/local/java)
#   {{CLASSPATH}} — JDK 8: .:$JAVA_HOME/lib/tools.jar:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib
#                   JDK 9+: .  (模块化后 tools.jar/dt.jar 已移除)
export JAVA_HOME={{JAVA_HOME}}
export CLASSPATH={{CLASSPATH}}
export PATH=$JAVA_HOME/bin:$PATH
