#!/bin/bash
# JDK 环境变量与 alternatives 管理
# 项目: dmp_ops/openjdk
#
# 设计要点:
#   1. JAVA_HOME 始终指向 ${jdk_link} 软链，切换版本只换软链，无需改 profile
#   2. 环境变量统一由 /etc/profile.d/openjdk.sh 承载(幂等重写)
#   3. CLASSPATH 分版本: JDK 8 含 tools.jar/dt.jar，JDK 9+ 已模块化移除

# alternatives 管理的命令清单
JDK_ALT_CMDS="java javac jar javadoc javap jarsigner keytool jshell jcmd jps jstack jmap jstat jinfo jhsdb serialver"

# 写回 options.conf(配置持久化)
Save_Option() {
  local key=$1
  local val=$2
  local conf="${openjdk_dir}/options.conf"
  [ -f "${conf}" ] || return 1
  if grep -q "^${key}=" "${conf}"; then
    sed -i "s@^${key}=.*@${key}=${val}@" "${conf}"
  else
    echo "${key}=${val}" >> "${conf}"
  fi
}

# 设置默认 JDK 环境变量
# 用法: Set_JDK_Env <java_home> <feature_ver>
Set_JDK_Env() {
  local jh=$1
  local ver=$2
  [ -x "${jh}/bin/java" ] || {
    echo "${CFAILURE}Invalid JAVA_HOME: ${jh}${CEND}"
    return 1
  }

  # 统一软链
  ln -snf "${jh}" "${jdk_link}"

  local classpath='.'
  [ "${ver}" == '8' ] && classpath='.:$JAVA_HOME/lib/tools.jar:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib'

  # 幂等重写(整文件覆盖，不追加)
  cat > /etc/profile.d/openjdk.sh << EOF
# /etc/profile.d/openjdk.sh — generated by dmp_ops/openjdk, DO NOT EDIT MANUALLY
export JAVA_HOME=${jdk_link}
export CLASSPATH=${classpath}
export PATH=\$JAVA_HOME/bin:\$PATH
EOF
  chmod 644 /etc/profile.d/openjdk.sh
  . /etc/profile.d/openjdk.sh
  return 0
}

# 清理 JDK 环境变量
Unset_JDK_Env() {
  rm -f /etc/profile.d/openjdk.sh
  [ -L "${jdk_link}" ] && rm -f "${jdk_link}"
  # 兼容历史遗留写法(oneinstack openjdk-18.sh 直接追加 /etc/profile)
  if [ -f /etc/profile ]; then
    sed -i '/export JAVA_HOME=/d' /etc/profile
    sed -i '/export CLASSPATH=/d' /etc/profile
    sed -i 's@\$JAVA_HOME/bin:@@' /etc/profile
    sed -i 's@\${JAVA_HOME}/bin:@@' /etc/profile
  fi
  echo "${CMSG}JDK environment variables cleaned${CEND}"
}

# alternatives 命令名(rhel: alternatives, debian 系: update-alternatives)
Alt_Cmd() {
  if [ "${Family}" == 'rhel' ]; then
    command -v alternatives 2>/dev/null || echo /usr/sbin/alternatives
  else
    command -v update-alternatives 2>/dev/null || echo /usr/bin/update-alternatives
  fi
}

# 注册 alternatives，priority = feature 版本 * 100
Register_Alternatives() {
  local jh=$1
  local ver=$2
  local alt=$(Alt_Cmd)
  [ -x "${alt}" ] || { echo "${CWARNING}alternatives command not found, skip${CEND}"; return 0; }

  local prio=$((ver * 100))
  local cmd
  for cmd in ${JDK_ALT_CMDS}; do
    [ -x "${jh}/bin/${cmd}" ] && \
      ${alt} --install /usr/bin/${cmd} ${cmd} ${jh}/bin/${cmd} ${prio} > /dev/null 2>&1
  done
  return 0
}

# 注销 alternatives
Unregister_Alternatives() {
  local jh=$1
  local alt=$(Alt_Cmd)
  [ -x "${alt}" ] || return 0

  local cmd
  for cmd in ${JDK_ALT_CMDS}; do
    [ -e "${jh}/bin/${cmd}" ] && \
      ${alt} --remove ${cmd} ${jh}/bin/${cmd} > /dev/null 2>&1
  done
  return 0
}

# 列出已安装的 JDK
# 输出: feature_ver full_ver vendor java_home [*]
List_JDK() {
  local cur=$(readlink -f "${jdk_link}" 2>/dev/null)
  local v jh full vendor mark
  for v in ${jdk_support_vers}; do
    jh=$(Detect_JAVA_HOME ${v})
    [ -z "${jh}" ] && continue
    full=$(Get_JDK_Full_Ver "${jh}")
    vendor=openjdk
    [[ "${jh}" =~ temurin ]] && vendor=temurin
    [[ "${jh}" == ${jdk_base_dir}/jdk-* ]] && vendor=temurin-bin
    mark=""
    [ -n "${cur}" ] && [ "$(readlink -f ${jh})" == "${cur}" ] && mark="*"
    echo "${v} ${full} ${vendor} ${jh} ${mark}"
  done
}

# 表格化输出已装 JDK
Print_JDK_Table() {
  local rows=$(List_JDK)
  if [ -z "${rows}" ]; then
    echo "${CWARNING}No OpenJDK installed by this toolkit was found${CEND}"
    return 1
  fi
  printf "%-8s %-18s %-14s %-45s %s\n" "VERSION" "FULL" "VENDOR" "JAVA_HOME" "DEFAULT"
  echo "${rows}" | while read v full vendor jh mark; do
    printf "%-8s %-18s %-14s %-45s %s\n" "${v}" "${full}" "${vendor}" "${jh}" "${mark}"
  done
  return 0
}

# 切换默认 JDK
Switch_JDK() {
  local ver=$1
  local jh=$(Detect_JAVA_HOME ${ver})
  [ -z "${jh}" ] && {
    echo "${CFAILURE}OpenJDK ${ver} is not installed.${CEND}"
    echo "Run: ./install.sh --jdk_option $(Ver_To_Option ${ver})"
    return 1
  }

  Set_JDK_Env "${jh}" "${ver}" || return 1
  Register_Alternatives "${jh}" "${ver}"

  local alt=$(Alt_Cmd)
  if [ -x "${alt}" ]; then
    local cmd
    for cmd in ${JDK_ALT_CMDS}; do
      [ -x "${jh}/bin/${cmd}" ] && ${alt} --set ${cmd} ${jh}/bin/${cmd} > /dev/null 2>&1
    done
  fi

  Save_Option jdk_current_ver "${ver}"
  echo "${CSUCCESS}Default JDK switched to: $(${jdk_link}/bin/java -version 2>&1 | head -1)${CEND}"
  echo "  JAVA_HOME: ${jdk_link} -> ${jh}"
  echo "${CWARNING}Note: run 'source /etc/profile.d/openjdk.sh' in existing shells;${CEND}"
  echo "${CWARNING}      running JVM processes must be restarted to take effect.${CEND}"
  return 0
}
